### ISSUE TITLE
kindlegen

### ISSUE THREAD

**Issue by Dnllns** [Carleslc/InMangaKindle#10]
Hola, parece que kindlegen ya no esta descargable desde amazon.
Hay algun link para descargar el binario?

**Comment by Carleslc** [comment]
Parece que ahora está incluido con [Kindle Previewer](https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765261).

¿Qué sistema operativo usas?

Si usas MacOS / Linux tendrás que extraerlo de la aplicación y moverlo al path: `cp /Applications/Kindle\ Previewer\ 3.app/Contents/lib/fc/bin/kindlegen /usr/local/bin/kindlegen`.

Si usas Windows, una vez lo tengas, ¿podrías decirme si se añade automáticamente al PATH al instalar el Kindle Previewer? En el instalador si se extrae está en `KindlePreviewerInstaller/肟/fc/bin/kindlegen.exe`, pero es posible que se añada automáticamente al PATH una vez instalado.

**Comment by Dnllns** [comment]
Muchas gracias por la pronta respuesta, me ha servido de mucho :)
Por cierto, en Windows 10 se añade al path durante la instalación.  Salu2!!
