### ISSUE TITLE
[503] https://inmanga.com/manga/getMangasConsultResult

### ISSUE THREAD

**Issue by Carleslc** [Carleslc/InMangaKindle#11]
https://twitter.com/Aqua_matt/status/1375623907508682752

**Comment by Carleslc** [comment]
Algunas opciones para modificar el programa:

- Obtener las cookies con un headless browser https://phantomjs.org/
- https://github.com/Anorov/cloudflare-scrape
- https://github.com/venomous/cloudscraper

**Comment by Carleslc** [comment]
El error 503 es debido a la protección DDoS de Cloudflare, usada por el servicio de inmanga.com (https://support.cloudflare.com/hc/es-es/articles/200170076--Qu%C3%A9-hace-el-modo-I-m-Under-Attack-)

Normalmente es un error temporal debido a un volumen muy alto de peticiones realizadas. Si te ocurre el error, vuelve a intentarlo en unas horas.

Si el error persiste, es posible que deba tenerse en cuenta a la hora de realizar las peticiones o que se deba cambiar la página para las descargas.

**Comment by Carleslc** [comment]
El modo offline añadiendo la opción `--cache` sigue funcionando correctamente para convertir los capítulos descargados previamente.

**Comment by tolete12** [comment]
Buenas tardes.
He conseguido arreglar el problema del error 503 que tiene este programa. Me gustaría hacer un Merge Request, sin embargo, me da algunos errores porque tengo GIT en Windows y la carpeta del Kindlegen (Linux y OSX) contiene algun caracter que Windows no acepta.
¿Como podemos poner en común lo que tengo? Si quitas los ":" que hay en el nombre de la carpeta, puedo hacer un push a una rama.

**Comment by Carleslc** [comment]
> Buenas tardes.
> He conseguido arreglar el problema del error 503 que tiene este programa. Me gustaría hacer un Merge Request, sin embargo, me da algunos errores porque tengo GIT en Windows y la carpeta del Kindlegen (Linux y OSX) contiene algun caracter que Windows no acepta.
> ¿Como podemos poner en común lo que tengo? Si quitas los ":" que hay en el nombre de la carpeta, puedo hacer un push a una rama.

¿Qué es lo que has hecho para arreglarlo? Este error es de naturaleza temporal y en estos momentos no ocurre (el programa es funcional a fecha de 19/05/2021). Ocurrió durante unos días en marzo, y es posible que ocurra de nuevo en el futuro.

Para poder subir los cambios deberías poder crear una [pull request](https://github.com/Carleslc/InMangaKindle/pulls). Haz fork si no lo has hecho y commit de tus cambios y luego pull request para que pueda revisarlo y hacer merge.

He quitado los `:` de la carpeta que te da conflictos. El contenido aunque no pueda abrirse desde Windows (el archivo es para OSX o Linux) no debería darte problemas para hacer commit sin modificarlo.

¡Gracias por tu aportación!

**Comment by tolete12** [comment]
Esta mañana he vuelto a probar la herramienta sin modificar nada y seguía obteniendo el error 503:
![image](https://user-images.githubusercontent.com/26748420/118925848-b1ae4b00-b93f-11eb-84d6-ac65e4f55641.png)

Lo que he hecho es añadir la librería cloudscraper a las dependencias, y en el archivo manga.py he instanciado el objeto scraper y lo he utilizado en los get y post.

No puedo hacer push origin de mi rama, creo que necesito que me des permisos para hacer push. ¿Puedes echarle un ojo por favor?

Muchas gracias a ti por esta herramienta tan útil :)

**Comment by tolete12** [comment]
Nada, disculpa. Ya hice fork y subí los cambios ahí.
Este es el PR: https://github.com/Carleslc/InMangaKindle/pull/12

**Comment by Carleslc** [comment]
Ya está incluido en `master` y en la [versión 1.5](https://github.com/Carleslc/InMangaKindle/releases/tag/1.5).

Gracias!
