### ISSUE TITLE
'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by godoymario95** [Carleslc/InMangaKindle#13]
File "....\manga.py", line 280, in cache_convert
    manga2ebook(argv)

File ".....\AppData\Roaming\Python\Python310\site-packages\kindlecomicconverter\comic2ebook.py", line 74, in main
    makeBook(source)

File "....\AppData\Roaming\Python\Python310\site-packages\kindlecomicconverter\comic2ebook.py", line 1089, in makeBook
    imgDirectoryProcessing(os.path.join(path, "OEBPS", "Images"))
  File "....\AppData\Roaming\Python\Python310\site-packages\kindlecomicconverter\comic2ebook.py", line 526, in imgDirectoryProcessing raise RuntimeError(**"One of workers crashed. Cause: " + workerOutput[0][0], workerOutput[0][1])
("One of workers crashed. Cause: 'float' object cannot be interpreted as an integer"**, '  File "....\AppData\\Roaming\\Python\\Python310\\site-packages\\kindlecomicconverter\\comic2ebook.py", line 563, in imgFileProcessing\n    img.autocontrastImage()\n  File "...\AppData\\Roaming\\Python\\Python310\\site-packages\\kindlecomicconverter\\image.py", line 258, in autocontrastImage\n    self.image = ImageOps.autocontrast(Image.eval(self.image, lambda a: 255 * (a / 255.) ** gamma))\n  File "...\AppData\\Roaming\\Python\\Python310\\site-packages\\PIL\\Image.py", line 3107, in eval\n    return image.point(args[0])\n  File "...\\AppData\\Roaming\\Python\\Python310\\site-packages\\PIL\\Image.py", line 1680, in point\n    return self._new(self.im.point(lut, mode))\n')

**Comment by Carleslc** [comment]
Parece algo relacionado con el kindlecomicconverter. Cuál es el comando completo que tratas de ejecutar?

**Comment by godoymario95** [comment]
Buenas,
el comando es el que se describe como ejemplo:

![image](https://user-images.githubusercontent.com/14913357/141143519-eaf0d80b-f6d0-4f44-864e-c8c037e1b10c.png)

**Comment by tolete12** [comment]
@godoymario95 @Carleslc yo he tenido ayer el mismo problema con Python 3.10, pero luego hice downgrade a Python 3.6 y volvió a funcionar sin problemas

**Comment by Carleslc** [comment]
A mí me funciona con la versión 3.9.1 de Python. También he probado con la 3.9.9 y funciona. Sin embargo en la Python 3.10.0 ya no.

Es un conflicto entre las versiones más recientes de Python y la dependencia kindlecomicconverter (KCC).

¿Qué versión de Python usas @godoymario95? Puedes verla con `python --version`

Por ahora prueba a bajar a una versión de Python inferior a 3.10.0 mientras esperamos que actualicen la dependencia KCC.

Ya hay alguna issue abierta sobre este error en el repo del KCC: https://github.com/ciromattia/kcc/issues/406

Si no lo actualizaran podemos probar a incluir el KCC en este repo con la solución planteada en el anterior enlace, pero considero que todavía es pronto para eso. Pero lo dejo como referencia:

Línea 258 de `kindlecomicconverter/image.py`
Modificar
`self.image = ImageOps.autocontrast(Image.eval(self.image, lambda a: 255 * (a / 255.) ** gamma))`
por
`self.image = ImageOps.autocontrast(Image.eval(self.image, lambda a: int(255 * (a / 255.) ** gamma)))`

**Comment by godoymario95** [comment]
Vale, queda solucionado hasta nuevo parche muchas gracias a todos por la ayuda.

Baje la versión a la 3.9.9 y funciono todo correctamente.

😊😊😊

**Comment by Carleslc** [comment]
En versiones más recientes de Kindle Comic Converter se solucionó este error de compatibilidad.

He sacado una nueva versión [1.7](https://github.com/Carleslc/InMangaKindle/releases) en la que ya se pueden utilizar versiones más recientes de Python.
Estoy utilizando [Python 3.13](https://www.python.org/downloads/latest/python3.13/).
