### ISSUE TITLE
Http Error 522 al intentar descargar

### ISSUE THREAD

**Issue by jmhs11** [Carleslc/InMangaKindle#14]
Buenas, parece ser que al intentar descargar los mangas desde InManga esta arrojando error 522 impidiendo así poder descargar los capitulos.

Entiendo que esto es un Scrapper de InManga pero hay alguna prevision para poder utilizar alguna pagina diferente?

Gracias

**Comment by Carleslc** [comment]
No sé si será algo temporal este error o que han cambiado algo en la página.

Por ejemplo con `python manga.py one piece --chapter last` me sale el 522:

`[522] https://pack-yak.intomanga.com/images/manga/raw/chapter/0/page/0/64c1d700-69f4-4ddc-babc-470e04caac28`

Cuando la imagen debería ser `https://pack-yak.intomanga.com/images/manga/One-Piece/chapter/1047/page/3/64c1d700-69f4-4ddc-babc-470e04caac28`

Puede que hayan cambiado la forma de obtener los capítulos y por eso sale chapter/0/page/0. En ese caso habría que revisarlo y adaptarlo.

> Entiendo que esto es un Scrapper de InManga pero hay alguna prevision para poder utilizar alguna pagina diferente?

Respecto a esta pregunta, sí, está previsto poder utilizar otras páginas para suplir este tipo de errores o añadir más mangas que no están en esa página, pero no puedo dar una fecha. Habría que refactorizar el código y abstraerlo para poder utilizar varias APIs/páginas.

**Comment by Carleslc** [comment]
Por ahora vuelve a funcionar sin tocar nada. Parece que el error era temporal.

**Comment by jmhs11** [comment]
Justo, acabo de probar y efectivamente funciona, muchas gracias por la actualización de estado. Estaré pendiente de nuevas releases y noticias!!
