### ISSUE TITLE
id PageList cannot be found

### ISSUE THREAD

**Issue by vgonisanz** [Carleslc/InMangaKindle#2]
Hi.

I tried to download a Manga using the repository. After clone and install dependencies and read the instructions I did:

`python3.6 manga.py --format png --chapters "last" Berserk`

and the script crash printing the website and I got the following error:

```
Traceback (most recent call last):
  File "manga.py", line 246, in <module>
    pages = html.find(id='PageList').find_all(True, recursive=False)
AttributeError: 'NoneType' object has no attribute 'find_all'
```
It seems that in the web code is not that id (I look for it in the complete trace), but using Firefox appear. 
How could I fix this?

**Comment by Carleslc** [comment]
Hello,

This script works using web scraping, which is inherently unstable. Previously chapter identifiers were extracted retrieving them from the chapter page (using 'PageList' id). Now identifiers have been moved to another endpoint so they were unreachable. It is fixed now.

Thanks for notify this crash and sorry for the inconveniences.

Enjoy!
