### ISSUE TITLE
ModuleNotFoundError: No module named 'kindlecomicconverter'

### ISSUE THREAD

**Issue by Alfacentauriii** [Carleslc/InMangaKindle#4]
Cuando intento descargar algún capítulo con formato epub me aparece el siguiente error: 

Traceback (most recent call last):
  File "manga.py", line 291, in <module>
    from kindlecomicconverter.comic2ebook import main as manga2ebook
ModuleNotFoundError: No module named 'kindlecomicconverter'

Cuando lo intento descargar en PDF me aparece otro error:

Traceback (most recent call last):
  File "manga.py", line 267, in <module>
    import img2pdf
ModuleNotFoundError: No module named 'img2pdf'

**Comment by Carleslc** [comment]
¿Has instalado los módulos correspondientes?

`pip install kindlecomicconverter` (o en formato binario: https://github.com/ciromattia/kcc#binary-releases)
`pip install img2pdf`

**Comment by Alfacentauriii** [comment]
Sí, exacto, me faltaba instalar esos 2 módulos, ahora funciona todo perfectamente, qué despistada soy a veces. Muchas gracias por el programa y por tu respuesta.
