### ISSUE TITLE
ModuleNotFound error: No module called "requests"

### ISSUE THREAD

**Issue by sebadnox** [Carleslc/InMangaKindle#5]
Hello everyone. When i try to open this program by typing "phyton manga.py" or "phyton manga.py -h" it shows me a message saying:

Traceback (most recent call last):
  File "manga.py", line 8, in <module>
    from requests import get, post
ModuleNotFoundError: No module named 'requests'

I dont know what i´m doing wrong. 
Thank you in advance :(

**Comment by Carleslc** [comment]
Have you fixed it?

Seems like you forgot to install the [dependencies](https://github.com/Carleslc/InMangaKindle#dependencias):

`pip install --user -r dependencies.txt` or `pip3 install --user -r dependencies.txt`

**Comment by sebadnox** [comment]
Hello again. That´s exactly what did happen. I solved it by installing all the missing dependences. Greetings.
