### ISSUE TITLE
Al hacer cualquier búsqueda: Manga "nombre" not found

### ISSUE THREAD

**Issue by kurai021** [Carleslc/InMangaKindle#6]
Al parecer estos últimos días InManga ha hecho alǵun cambio que impide que el query se complete

**Comment by kurai021** [comment]
he hecho pruebas con curl y obtengo el HTML con las url de cada manga relacionado a mi término de busqueda sin mayores problemas, pero el output de Python solo me trae algunos divs sin el contenido que se hará scrapping

**Comment by kurai021** [comment]
Creo que InManga ahora espera un header más elavorado al hacer el request, puedes ver los cambios que hice al script desde la línea 187 aquí:

https://gist.github.com/kurai021/b2d85fe6a5f6523c8f2adbfe7947622c

**Comment by Carleslc** [comment]
Muchas gracias por tu aportación 😃

Parece que cambiando la línea
```
search_href = BeautifulSoup(search.content, 'html.parser').find_all(True, recursive=False)
```
por
```
search_href = BeautifulSoup(search.content, 'html.parser').find_all("a", href=True, recursive=False)
```
ya funciona. No haría falta el header más elaborado ni los filtros broadcastStatus y onlyFavorites, pero los dejo por si acaso.

Actualizado, gracias de nuevo 👍
