### ISSUE TITLE
Idioma

### ISSUE THREAD

**Issue by Twikzer** [Carleslc/InMangaKindle#7]
Falta una opcion para seleccionar en que idioma quieres el manga, ya que te lo baja en ingles

**Comment by Carleslc** [comment]
¿Qué manga estás tratando de descargar? En principio deberían de descargarse todos en español.

**Comment by Carleslc** [comment]
Cierro la issue pues el funcionamiento actual debería ser descargar en Español. Abre de nuevo con más información si no es así, gracias.
