### ISSUE TITLE
"Not Found" a tots els manga que cerc.

### ISSUE THREAD

**Issue by Mateo-asg** [Carleslc/InMangaKindle#8]
Hola,
He estat usant el teu codi durant uns mesos i funcionava perfecte, però fa una setmana cada vegada que cerc un manga per descarregar-lo hem surt el missatge de Not Found, no he canviat res del codi, i no se que fer perque no sé de programació, creus que podries ajudar-me?

He adjuntat una imatge del terminal.

Gràcies.
![Captura de pantalla 2020-01-14 a las 11 41 59](https://user-images.githubusercontent.com/59871627/72341752-f3334400-36c2-11ea-9f7f-747385141591.png)

**Comment by Carleslc** [comment]
Gràcies per reportar l'error. Ja està solucionat en la última versió publicada.

Pots descarregar-la aquí: https://github.com/Carleslc/InMangaKindle/releases/tag/1.2 o actualitzar el programa utilitzant git: `git pull`
